#!/bin/env bash

if [[ $# -gt 0 ]]; then
	case "$1" in
		mpd)
			if ! pgrep -u $UID -x mpd >/dev/null; then
				mpd > /dev/null 2>&1
			fi
		;;

		wm)
			wm=${2:-i3}

			echo "Launching wm $wm..."
			ck-launch-session dbus-launch --exit-with-session "$wm"
			unset wm
		;;

		wmcommon)
			start-pulseaudio-x11
			numlockx &
			/usr/libexec/polkit-mate-authentication-agent-1 &

			$HOME/bin/wallock --start-locker
			$HOME/bin/initscripts polybar &
			unclutter -idle 3 &
			$HOME/bin/initscripts mpcwatch &
			nm-applet &
			$HOME/bin/initscripts compton &
		;;

		polybar)
			killall -q polybar
			# Wait until the processes have been shut down
			while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

			polybar main
		;;

		mpcwatch)
			while [ 1 ]; do
				mpc idle player > /dev/null
				sleep 0.1s
				$HOME/bin/notify-info music
			done
		;;

		compton)
			compton --config $HOME/.config/compton/compton.conf
		;;
	esac
fi
