name: "Rust Cross OCI"
on: workflow_dispatch

env:
  REGISTRY_IMAGE: ghcr.io/theedward162/rust-cross

jobs:
  per-platform:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
            tag_prefix: amd64
          - os: macos-latest
            platform: linux/arm64
            tag_prefix: aarch64
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: rust-cross.Dockerfile
          tags: ${{ env.REGISTRY_IMAGE }}:${{ matrix.tag_prefix }}-${{ github.sha }}
          platform: ${{ matrix.platform }}
          push: true
  
  merge:
    runs-on: ubuntu-latest
    needs:
      - per-platform
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create merged manifest
        run: >
          docker buildx imagetools create -t ${{ env.REGISTRY_IMAGE }}:${{ github.sha }}
          ${{ env.REGISTRY_IMAGE }}:amd64-${{ github.sha }} 
          ${{ env.REGISTRY_IMAGE }}:aarch64-${{ github.sha }} 
