name: "Rust Cross"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the toolchain to use"
        required: true
        type: string

env:
  REGISTRY_IMAGE: ghcr.io/theedward162/rust-cross

jobs:
  release:
    strategy:
      matrix:
        base:
          - tag: bookworm-slim
            image: debian
          - tag: "3.21"
            image: alpine
          - tag: trixie-slim
            image: debian
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: rust-cross/rust-cross.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY_IMAGE }}:${{ inputs.version }}-${{ matrix.base.image }}-${{ matrix.base.tag }}
            ${{ env.REGISTRY_IMAGE }}:${{ inputs.version }}-${{ matrix.base.image }}-${{ matrix.base.tag }}-${{ github.sha }}
          push: true
          build-args: |
            BASE_IMAGE=${{ matrix.base.image }}
            BASE_TAG=${{ matrix.base.tag }}
            RUST_TOOLCHAIN=${{ inputs.version }}
