name: "Rust"
on:
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ghcr.io/theedward162/rust

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: rust-cross/rust.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY_IMAGE }}:slim-trixie
          push: true
          build-args: |
            BASE_OS=trixie-slim
